services:
  - type: web
    name: attendance
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: attendance-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: attendance
      - key: DB_USERNAME
        value: attendance
      - key: DB_PASSWORD
        generateValue: true

databases:
  - name: attendance-db
    plan: free
